src/simd/memchr2.rs
src/simd/memrchr2.rs
src/simd/memset.rs
src/simd/mod.rs
src/unicode/utf8.rs

Since [`offset_from_unsigned` has been stabilized](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.offset_from_unsigned), we can remove simd::distance now.

remove simd::distance

---

src/fuzzy.rs

Maybe I am misreading or misunderstanding the code, but it feels clearly buggy...

Improve readability of consider_as_equal

---

assets/Microsoft_logo_(1980).svg

fix(assets): remove extraneous Source: and License: elements
Per the SVG 2 Conformance Criteria:
A DOM node tree or subtree rooted at a given element is a conforming SVG
DOM subtree if it forms a SVG document fragment that adheres to the
specification described in this document (Scalable Vector Graphics (SVG)
Specification). Specifically, it:
- is rooted by an ‘svg’ element in the SVG namespace,
[...]
With the extra headers, both GitHub's preview function, Firefox and
Gwenview (KDE) fails to render the vector image:
GitHub:
Error rendering embedded code
Invalid image source.
Firefox:
XML Parsing Error: XML or text declaration not at start of entity
Location: https://raw.githubusercontent.com/microsoft/edit/refs/heads/main/assets/Microsoft_logo_(1980).svg
Line Number 3, Column 1:
<?xml …

Fix SVG by moving the processing instruction to the start

---

.cargo/release.toml

MinGW toolchains just don't support these flags

Don't apply MSVC compile flags for non-MSVC toolchains

---

src/lib.rs
src/sys/unix.rs

Fixes https://github.com/microsoft/edit/issues/66. Still doesn't have color in Terminal.app, though.
---
This PR was vibe coded with VS Code & Copilot Agent mode. It's fine to close if there's a concurrent effort or something more official. I just wanted to demonstrate it could be done. That said, `cargo test` passes locally 👍

Add support for macOS and BSD

---

Cargo.toml

opt level = s is clearly used a few lines below this comment.
I updated the comment to just mention this :)

Update Cargo.toml to remove "future" in comment

---

src/bin/edit/draw_menubar.rs

Currently, there's a conflict of access keys in the Edit menu – both Redo and Replace are assigned to `R`. This means that the Replace feature can't be accessed by Alt followed by a letter.
With this one-character bugfix, I've changed Replace's access key to `L`, which doesn't conflict with any of the other items in this menu.
This matches the access key used in old-school MS-DOS Edit.
Closes #56

Fix access key for Replace in Edit menu

---

Cargo.toml

Updated the Cargo.toml with:
1. Added license, the same as the repository.
2. Added repository URL.
3. Added [incremental](https://doc.rust-lang.org/cargo/reference/profiles.html#incremental) to the release profile to improve re-compile times.
4. Added minimum required [Rust version](https://doc.rust-lang.org/cargo/reference/rust-version.html?highlight=rust-version#rust-version) just like the global.json for .NET builds.
5. Added Homepage URL.

Improved the Cargo.toml

---

src/buffer/mod.rs

This fixes issue #112 , where pressing Shift+Tab at the beginning of an empty line would cause the program to panic.
We now check at the very beginning of the loop whether the offset is greater than or equal to the replacement length, instead of doing it after attempting the action.
Closes #112

Solve Panic when pressing Shift + Tab in an empty line

---

src/sys/unix.rs

In Linux, it is possible for the `LANGUAGE` variable to exist but have a empty value,
Before: 
After:

Fix language match on Linux (Unix?)

---

Cargo.toml
README.md
src/tui.rs
src/unicode/measurement.rs

This pull requests fixes minor spelling mistakes in the code.
While the typos fixed are very small, this fix is important for a project made by a large corporation.
**Also adds winget reference to README.md**

Fix multiple spelling mistakes

---

src/bin/edit/main.rs

xterm defaults to an 8-bit character encoding for Alt+key presses.
Private mode 1036 temporarily enables the `metaSendsEscape` resource:
`Ps = 1 0 3 6`  ⇒  Send `ESC`   when Meta modifies a key, _xterm_.
Fixes #197

Request DEC mode 1036 (Alt+char sends ESC)

---

src/bin/edit/documents.rs

The fix in #193 required us to create FileIds even for nonexistent files.
That broke the creation of nonexistent files.

Restore the ability to edit a new nonexistent file

---

src/simd/memchr2.rs
src/simd/memrchr2.rs

Fix page size for aarch64-apple-darwin in test

---

src/input.rs
src/vt.rs

A lending iterator ties the item lifetime to the borrow of `self`, so writing the lifetimes that way Just Works.
I also make `input::Stream` an actual Iterator, since it had no reason not to be.

Remove unsafe lifetime transmute in `vt::Stream`

---

src/arena/release.rs
src/arena/string.rs
src/bin/edit/main.rs
src/buffer/mod.rs
src/buffer/navigation.rs
src/fuzzy.rs
src/input.rs
src/sys/unix.rs
src/tui.rs
src/unicode/measurement.rs
src/vt.rs
tools/grapheme-table-gen/src/main.rs

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling)
The misspellings have been reported at https://github.com/jsoref/microsoft-edit/actions/runs/15175668756/attempts/1#summary-42675376659
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/microsoft-edit/actions/runs/15175668818/attempts/1#summary-42675376754

Fix various spelling errors

---

src/bin/edit/draw_editor.rs
src/bin/edit/draw_menubar.rs
src/bin/edit/localization.rs
src/bin/edit/main.rs
src/bin/edit/state.rs

Since issue had `E-help-wanted`, I figured I can try to implement the Goto. Would be glad to see the feedback. I haven't done any localization yet.
Closes #21

Add a "Go to Line/Column" dialog

---

src/bin/edit/main.rs

Allow bulk opening multiple files

---

src/bin/edit/draw_menubar.rs
src/bin/edit/localization.rs

Closes https://github.com/microsoft/edit/issues/187
Translations done using an LLM, but I guess it is fine for now 😅

Add the Document Picker entry to View menu

---

src/bin/edit/localization.rs

Fix lang matcher not picking the most specific hit

---

src/buffer/mod.rs
src/icu.rs

Fix Search & Replace deadlock

---

src/bin/edit/draw_editor.rs
src/bin/edit/draw_menubar.rs

Fix minor issues around Go to Line/Column

---

src/bin/edit/draw_editor.rs
src/bin/edit/draw_filepicker.rs
src/bin/edit/draw_menubar.rs
src/bin/edit/draw_statusbar.rs
src/bin/edit/main.rs
src/bin/edit/state.rs
src/tui.rs

This PR offers a resolution for https://github.com/microsoft/edit/issues/48
- Adds support for accelerator characters in any button's label
- Allow checkboxes, brackets, accelerator chars to be drawn conditionally with ButtonStyle
Existing accelerator-enabled buttons draw as before:
But other buttons may now visualize their accelerator character:
Behavior for other localisations:

Unify button label drawing in a shared routine `button_label`

---

src/bin/edit/documents.rs
src/bin/edit/draw_filepicker.rs
src/bin/edit/main.rs
src/bin/edit/state.rs
src/sys/windows.rs

This could still be improved in the future by showing the drive list (and perhaps favorite folders) separately from the file list. But I think we can do that at some point in the future.
Closes #102

Windows: Add a drive selector to the file picker

---

src/bin/edit/draw_editor.rs
src/bin/edit/draw_filepicker.rs
src/bin/edit/draw_statusbar.rs
src/tui.rs

One PR removed the `sys` import, the other started using it.
This also fixes the formatting of code introduced in #276.

Fix compilation after an incorrect merge

---

src/bin/edit/draw_editor.rs
src/bin/edit/draw_filepicker.rs
src/bin/edit/draw_statusbar.rs

Fix consume_shortcut calls not checking for focus

---

src/tui.rs

Currently the doc test for `src/tui.rs` fails as follows:
```
---- src\tui.rs - tui (line 91) stdout ----
error[E0061]: this method takes 3 arguments but 2 arguments were supplied
--> src\tui.rs:135:16
|
46   |         if ctx.button("button", "Click me!") {
|                ^^^^^^----------------------- argument #3 of type `ButtonStyle` is missing
|
note: method defined here
--> C:\Users\rhysd\Dev\edit\src\tui.rs:1989:12
|
1989 |     pub fn button(&mut self, classname: &'static str, text: &str, style: ButtonStyle) -> bool {
|            ^^^^^^
help: provide the argument
|
46   |         if ctx.button("button", "Click me!", /* ButtonStyle */) {
|                                            +++++++++++++++++++
error: aborting due to 1 previous error
```
This PR fixes it and I confirmed all …

Fix building doc test for `tui` module

---

src/bin/edit/localization.rs
src/bin/edit/main.rs
src/helpers.rs

An example for an issue with `i32` can be seen in #315,
but I suspect there's more issues like that elsewhere.

Avoid CoordType overflow by making it isize

---

src/bin/edit/draw_editor.rs
src/buffer/mod.rs

This PR fixes the issue twice for double the fun: It now explicitly
checks for a non-empty needle and also ensures the selection is
non-empty which ensures `if !self.has_selection()` works correctly.
Closes #273

Fix a search deadlock if there's no needle

---

src/tui.rs

For large files, `delta_y * scrollable_height` can cause an int overflow, resulting in a negative `scroll_offset` and broken behavior. This PR fixes it by casting to f32 for calculation.
Scroll bar doesn't make it to the end of the file and jumps back to 0
https://github.com/user-attachments/assets/70b2c267-8528-4971-bc4e-17a082fd1f02
Scroll bar continues normally
https://github.com/user-attachments/assets/d470ced9-89a6-4764-9da2-1c3a1fa85022

Fix scrollbar int overflow in drag handling

---

.pipelines/release.yml

Perhaps the next time we make a release, Windows Defender won't consider it a virus?

build: make the build pipeline produce the ZIP

---

src/bin/edit/draw_filepicker.rs
src/bin/edit/main.rs
src/bin/edit/state.rs

Avoid changing file picker selection when typing

---

.github/workflows/pr.yml
Cargo.toml
src/bin/edit/draw_statusbar.rs
src/bin/edit/main.rs

Add a CI check for PRs

---

src/bin/edit/main.rs
src/lib.rs
src/path.rs

This is an alternative approach to #176.
Closes #176

Remove dependency on os_string_truncate

---

src/bin/edit/state.rs

`DisplayablePathBuf::from_string` allocates two heap memories for `PathBuf` and `Cow::Owned`. However it can be stored as `Cow::Borrowed` because `String` guarantees UTF-8 sequence. This can remove one redundant heap allocation. ~~As a bonus `DisplayablePathBuf::from_path` can be reused so the code is more simplified.~~

Remove redundant heap allocation in `DisplayablePathBuf::from_string`

---

src/buffer/gap_buffer.rs

marking `Vec<T>` as source code, not HTML tag

Fix `Vec<T>` formatting in docs

---

.vscode/launch.json

CodeLLDB is the second most popular extension for debugging with LLDB in VSCode, so I think it would be useful for a lot of people to add a launch option for it as well.

Add a CodeLLDB launch option for VSCode

---

src/buffer/mod.rs

Closes #431
Not sure if there was something else planned, but basically reverting two small changes from #406 fixes the issue.
Well, only the `TextBuffer::edit_end` one fixes the reported issue, but there was no point leaving the issue in the undo/redo code.

Make sure margin gets updated

---

.github/workflows/winget.yml

With the latest winget-create release, the preferred method for providing the GitHub token in CI/CD environment is via the environment variable `WINGET_CREATE_GITHUB_TOKEN`. Removed use of `--token` and switched to environment variable. See https://aka.ms/winget-create-token for details.

Update WinGet publish script to use env var instead of --token

---

README.md
build.rs
src/arena/release.rs
src/arena/scratch.rs
src/icu.rs
src/sys/unix.rs
src/sys/windows.rs

This PR was tested on Ubuntu with:
```
EDIT_CFG_ICUUC_SONAME=libicuuc.so.74
EDIT_CFG_ICUI18N_SONAME=libicui18n.so.74
EDIT_CFG_ICU_RENAMING_VERSION=74
cargo build --config .cargo/release.toml --release
```
Search & Replace now works flawlessly. I hope that package maintainers
will be able to make use of this when ingesting future versions of Edit.
Closes #172

Make the ICU SONAME configurable

---

src/sys/unix.rs

The code zeroed STATE.utf8_len before using it as 
a slice index, which causes leftover UTF-8 bytes from 
previous reads to be discarded instead of prepended to the bu﻿ffer

Fix UTF-8 buffer prepending in read_stdin

---

src/buffer/mod.rs

Fix file truncation when writing with ICU

---

.cargo/release.toml

Enable `default` features for `build-std`

---

src/tui.rs

Implement a shortcut for selecting the entire line using Ctrl+L to align with VSCode shortcuts.

Add Ctrl+L shortcut to select whole line

---

src/lib.rs
src/simd/lines_bwd.rs
src/simd/lines_fwd.rs

Benchmark results on LA664:
- LASX
```
simd/lines_fwd/1        time:   [2.4046 ns 2.4076 ns 2.4118 ns]
thrpt:  [395.42 MiB/s 396.10 MiB/s 396.60 MiB/s]
change:
time:   [+20.046% +20.332% +20.762%] (p = 0.00 < 0.05)
thrpt:  [−17.193% −16.896% −16.699%]
Performance has regressed.
simd/lines_fwd/8        time:   [8.4050 ns 8.4114 ns 8.4192 ns]
thrpt:  [906.19 MiB/s 907.03 MiB/s 907.72 MiB/s]
change:
time:   [+4.9243% +5.0308% +5.1538%] (p = 0.00 < 0.05)
thrpt:  [−4.9012% −4.7898% −4.6932%]
Performance has regressed.
simd/lines_fwd/128      time:   [35.622 ns 35.650 ns 35.685 ns]
thrpt:  [3.3406 GiB/s 3.3439 GiB/s 3.3465 GiB/s]
change:
time:   [−66.111% −65.957% −65.864%] (p = 0.00 < 0.05)
thrpt:  [+192.94% +193.74% +195.08%]
Performance has improved.
simd/lines_fwd/1024     time:   [53.349 …
```

Add SIMD impls of `lines_fwd` and `lines_bwd` for LoongArch

---

src/bin/edit/main.rs
src/bin/edit/state.rs

Fixes #522
This is a small change that ensures that files that have unsaved changes are shown in the terminal title with an asterisk. It's updated on each change and undo/redo action:
https://github.com/user-attachments/assets/c7f7edc2-2933-4f43-be4d-a14d99dc7f85

Indicate unsaved work with U+25CF in the terminal title

---

.devcontainer/devcontainer.json

Adds a `.devcontainer` folder with a single `devcontainer.json` file that allows you to develop in a rust-nightly ready container.
If using one of the supported editors (https://containers.dev/supporting) for your regular development and for any reason would prefer to run/test/compile in a container-based environment, this gets you a ready-to-go solution.
Issue #494

Add initial devcontainer configuration for Rust environment

---

src/buffer/mod.rs

Fix undo grouping of backspacing

---

src/simd/lines_bwd.rs
src/simd/lines_fwd.rs
src/simd/memchr2.rs
src/simd/memset.rs

Prior to Rust `nightly-2025-08-08`, LoongArch SIMD intrinsics used distinct vector types such as `v4i32`, `v8i32`, and others. Passing data between intrinsics of different types required explicit `mem::transmute` calls, introducing unnecessary boilerplate and complexity.
This change adopts unified `m128i` and `m256i` types for all LoongArch SIMD intrinsics, eliminating redundant conversions and simplifying cross-intrinsic data handling.

Use unified data types in LoongArch SIMD intrinsics

---

src/tui.rs

Separate scrolling from clicking

---

src/bin/edit/edit.exe.manifest

So, it turns out that `supportedOS` was being ignored because it was taken to be in the default `asm.v1` namespace. :)

windows: fix the compatibility section of the manifest
